@baseUrl = http://localhost:3000
@adminToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImNhbXBJZCI6MSwicm9sIjoiU1lTVEVNX0FETUlOIiwianRpIjoiZGZhOTE1OGEtMmEyNy00ZmFkLThjOGQtNTY0NWM1M2E4ZmY2IiwiaWF0IjoxNzc1MjcxMjY0LCJleHAiOjE3NzUyNzI0NjR9.rJBvfGNhIEIJkA3gfZR3WALloANUc4W46AAXr5kYzME
@workerToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImNhbXBJZCI6MSwicm9sIjoiV09SS0VSIiwianRpIjoiZDBlN2UxNjQtZDYyZS00ZTkyLTk4NDUtMTZiZjgxMWUyNmM5IiwiaWF0IjoxNzc1MjcxMjg3LCJleHAiOjE3NzUyNzI0ODd9.MVQT-BZZAl08-qXYLTWkpQYYhDlmNe4JNr_xAl1IdIk
@resourceToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImNhbXBJZCI6MSwicm9sIjoiUkVTT1VSQ0VfTUFOQUdFTUVOVCIsImp0aSI6IjQ4ZGNhNWMwLWQwOWUtNDQwZC1iZTQ1LTQ0Y2U0NjFhMTA5NyIsImlhdCI6MTc3NTI3MTMwOCwiZXhwIjoxNzc1MjcyNTA4fQ.LhYyQUfPOwUEiJAL5LzROBI7nAgouL6PuDRW7HsZvmw
@travelToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImNhbXBJZCI6MSwicm9sIjoiVFJBVkVMX01BTkFHRVIiLCJqdGkiOiI1OWQxZmY0YS04ZDJkLTQ0NDMtYTAxZS1hMTgzYzFhM2VlNGEiLCJpYXQiOjE3NzUyNzEzMzcsImV4cCI6MTc3NTI3MjUzN30.6oHfdhBct2CWbjikees-LE88k8GIvf54J4X4t6PVX9A
@visitorToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImNhbXBJZCI6MSwicm9sIjoiVFJBVkVMX01BTkFHRVIiLCJqdGkiOiIwYTVkYWFhNy04MTMzLTRiNjUtOWFlMC04M2JiODQxODQ1ZjIiLCJpYXQiOjE3NzUyNzEzNTksImV4cCI6MTc3NTI3MjU1OX0.53I8Yr8nNnhGn77jnDawWyuLxfd0h00LqVlmnTv3yaI
@logoutToken =

### Login SYSTEM_ADMIN
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "admin_camp1",
  "password": "Seed1234!",
  "campId": 1
}

### Login WORKER
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "worker_camp1",
  "password": "Seed1234!",
  "campId": 1
}

### Login RESOURCE_MANAGEMENT
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "resource_camp1",
  "password": "Seed1234!",
  "campId": 1
}

### Login TRAVEL_MANAGER
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "travel_camp1",
  "password": "Seed1234!",
  "campId": 1
}

### Login VISITOR
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "visitor_camp1",
  "password": "Seed1234!",
  "campId": 1
}

### No token 401
GET {{baseUrl}}/api/users

### SYSTEM_ADMIN accesses users
GET {{baseUrl}}/api/users
Authorization: Bearer {{adminToken}}

### VISITOR forbidden 403
GET {{baseUrl}}/api/users
Authorization: Bearer {{visitorToken}}

### WORKER accesses occupations
GET {{baseUrl}}/api/occupations
Authorization: Bearer {{workerToken}}

### WORKER forbidden 403
GET {{baseUrl}}/api/users
Authorization: Bearer {{workerToken}}

### RESOURCE_MANAGEMENT accesses inventory
GET {{baseUrl}}/api/camp-inventory
Authorization: Bearer {{resourceToken}}

### TRAVEL_MANAGER accesses expeditions
GET {{baseUrl}}/api/expeditions
Authorization: Bearer {{travelToken}}

### TRAVEL_MANAGER forbidden 403
GET {{baseUrl}}/api/users
Authorization: Bearer {{travelToken}}

### Logout
POST {{baseUrl}}/api/auth/logout
Authorization: Bearer {{adminToken}}

### Access after logout 401
GET {{baseUrl}}/api/users
Authorization: Bearer {{logoutToken}}

### Token renewal check
GET {{baseUrl}}/api/occupations
Authorization: Bearer {{workerToken}}

### BLOCK 1 - ADMISSION REQUESTS

### [SHOULD 401] admission requests list - no token
GET {{baseUrl}}/api/admission-requests

###

### [SHOULD 200] admission requests list - admin
GET {{baseUrl}}/api/admission-requests
Authorization: Bearer {{adminToken}}

###

### [SHOULD 403] admission requests list - worker
GET {{baseUrl}}/api/admission-requests
Authorization: Bearer {{workerToken}}

###

### [SHOULD 403] admission requests list - resource
GET {{baseUrl}}/api/admission-requests
Authorization: Bearer {{resourceToken}}

###

### [SHOULD 403] admission requests list - travel
GET {{baseUrl}}/api/admission-requests
Authorization: Bearer {{travelToken}}

###

### [SHOULD 403] admission requests list - visitor
GET {{baseUrl}}/api/admission-requests
Authorization: Bearer {{visitorToken}}

###

### BLOCK 1 - PERSONS

### [SHOULD 200] persons list - admin
GET {{baseUrl}}/api/persons
Authorization: Bearer {{adminToken}}

###

### [SHOULD 200] persons list - worker
GET {{baseUrl}}/api/persons
Authorization: Bearer {{workerToken}}

###

### [SHOULD 200] persons list - resource
GET {{baseUrl}}/api/persons
Authorization: Bearer {{resourceToken}}

###

### [SHOULD 200] persons list - travel
GET {{baseUrl}}/api/persons
Authorization: Bearer {{travelToken}}

###

### [SHOULD 200] persons list - visitor
GET {{baseUrl}}/api/persons
Authorization: Bearer {{visitorToken}}

###

### [SHOULD 200] person detail - admin
GET {{baseUrl}}/api/persons/1
Authorization: Bearer {{adminToken}}

###

### [SHOULD 403] person detail - worker
GET {{baseUrl}}/api/persons/1
Authorization: Bearer {{workerToken}}

###

### [SHOULD 403] person detail - visitor
GET {{baseUrl}}/api/persons/1
Authorization: Bearer {{visitorToken}}

###

### BLOCK 1 - SYSTEM USERS

### [SHOULD 401] users list - no token
GET {{baseUrl}}/api/users

###

### [SHOULD 200] users list - admin
GET {{baseUrl}}/api/users
Authorization: Bearer {{adminToken}}

###

### [SHOULD 403] users list - worker
GET {{baseUrl}}/api/users
Authorization: Bearer {{workerToken}}

###

### [SHOULD 403] users list - resource
GET {{baseUrl}}/api/users
Authorization: Bearer {{resourceToken}}

###

### [SHOULD 403] users list - travel
GET {{baseUrl}}/api/users
Authorization: Bearer {{travelToken}}

###

### [SHOULD 403] users list - visitor
GET {{baseUrl}}/api/users
Authorization: Bearer {{visitorToken}}

###