@baseUrl = http://localhost:3000
@workerToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImNhbXBJZCI6MSwicm9sIjoiV09SS0VSIiwianRpIjoiZDBlN2UxNjQtZDYyZS00ZTkyLTk4NDUtMTZiZjgxMWUyNmM5IiwiaWF0IjoxNzc1MjcxMjg3LCJleHAiOjE3NzUyNzI0ODd9.MVQT-BZZAl08-qXYLTWkpQYYhDlmNe4JNr_xAl1IdIk
@adminToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImNhbXBJZCI6MSwicm9sIjoiU1lTVEVNX0FETUlOIiwianRpIjoiMmVhZTc1NDUtN2MxZS00N2EyLTliODYtZDI0NDkyNjdhYzA4IiwiaWF0IjoxNzc1MzQ1MDc0LCJleHAiOjE3NzUzNDYyNzR9.EMJaQdVI97ZhyYegeOmnXeARbVKy1op4s7QVoho-UUs
@resourceToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImNhbXBJZCI6MSwicm9sIjoiUkVTT1VSQ0VfTUFOQUdFTUVOVCIsImp0aSI6IjFlMjEyNWM1LThlOTMtNDE2Ni1iNzEwLWFjYTU4MmFkYmUxMSIsImlhdCI6MTc3NTM0NTA4NCwiZXhwIjoxNzc1MzQ2Mjg0fQ.dvGmtHR0VjJTa16Q_W7uIBebqmnqD9ilbnZTVd_GE7k
@travelToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImNhbXBJZCI6MSwicm9sIjoiVFJBVkVMX01BTkFHRVIiLCJqdGkiOiIxMzYyZWY4NC0zYWU4LTRiZDEtOTE0OS1iZDFlZTFkMmU3ZjEiLCJpYXQiOjE3NzUzNDUxMTEsImV4cCI6MTc3NTM0NjMxMX0.7qiCjQeIx8mw_T8qAjIpV6hkQ272gdrY3mWT0KVKeEk

### 2.1 [LOGIN] SYSTEM_ADMIN
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "admin_camp1",
  "password": "Seed1234!",
  "campId": 1
}

###

### 2.2 [LOGIN] RESOURCE_MANAGEMENT
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "resource_camp1",
  "password": "Seed1234!",
  "campId": 1
}

###

### 2.3 [LOGIN] WORKER
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "worker_camp1",
  "password": "Seed1234!",
  "campId": 1
}

###

### 2.4 [LOGIN] WORKER
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "worker_camp1",
  "password": "Seed1234!",
  "campId": 1
}

###

### 2.5 [LOGIN] TRAVEL_MANAGER
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "travel_camp1",
  "password": "Seed1234!",
  "campId": 1
}

###

### 2.6 GET Camp Inventory - Admin (Expect 200)
GET {{baseUrl}}/api/camp-inventory
Authorization: Bearer {{adminToken}}

###

### 2.7 GET Camp Inventory - Resource Management (Expect 200)
GET {{baseUrl}}/api/camp-inventory
Authorization: Bearer {{resourceToken}}

###

### 2.8 GET Camp Inventory - Worker (Expect 403)
GET {{baseUrl}}/api/camp-inventory
Authorization: Bearer {{workerToken}}

###

### 2.9 GET Camp Inventory By Key - Admin (Expect 200)
GET {{baseUrl}}/api/camp-inventory/1/1
Authorization: Bearer {{adminToken}}

###

### 2.10 GET Camp Inventory By Key - Resource Management (Expect 200)
GET {{baseUrl}}/api/camp-inventory/1/1
Authorization: Bearer {{resourceToken}}

###

### 2.11 PUT Camp Inventory - Resource Management (Expect 200)
PUT {{baseUrl}}/api/camp-inventory/1/1
Authorization: Bearer {{resourceToken}}
Content-Type: application/json

{
  "minimumAlertAmount": "40.00"
}

###

### 2.12 PUT Camp Inventory - Admin (Expect 403)
PUT {{baseUrl}}/api/camp-inventory/1/1
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "minimumAlertAmount": "40.00"
}

###

### 2.13 POST Camp Inventory - Admin (Expect 403 ForbiddenException System Managed)
POST {{baseUrl}}/api/camp-inventory
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "campId": 1,
  "resourceTypeId": 1,
  "currentAmount": "1000",
  "minimumAlertAmount": "100"
}

###

### 2.14 DELETE Camp Inventory - Admin (Expect 403 ForbiddenException System Managed)
DELETE {{baseUrl}}/api/camp-inventory/1/1
Authorization: Bearer {{adminToken}}

###

### 2.15 GET Camp Inventory - Travel Manager (Expect 403 Forbidden)
GET {{baseUrl}}/api/camp-inventory
Authorization: Bearer {{travelToken}}