@baseUrl = http://localhost:3000
@adminToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImNhbXBJZCI6MSwicm9sIjoiU1lTVEVNX0FETUlOIiwianRpIjoiMjJhY2U5MmYtNTFjYy00NjhjLWFlYmUtYWNmMWM2MWMwYmM1IiwiaWF0IjoxNzc1NjM0MDk3LCJleHAiOjE3NzU2MzUyOTd9.MDhtz6-JIaAcXvkwE_7c6bJKTB1RrEMhfYt0rOdFOgE
@workerToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImNhbXBJZCI6MSwicm9sIjoiV09SS0VSIiwianRpIjoiOTFhOWRkN2EtMDFjYi00NzZiLWI2MDctMTkyMGJkZDBiYzBhIiwiaWF0IjoxNzc1NjM0MTE3LCJleHAiOjE3NzU2MzUzMTd9.Rf9dlmUuvnSKTN2gcwW8Vinq8At4eKFAt03bqNyAZ2Y
@resourceToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImNhbXBJZCI6MSwicm9sIjoiUkVTT1VSQ0VfTUFOQUdFTUVOVCIsImp0aSI6IjcxZjhhYTM1LTIxMWItNGVmZC1hNjM0LTRmNDUzZWQyMDliZSIsImlhdCI6MTc3NTYzNDU0NywiZXhwIjoxNzc1NjM1NzQ3fQ.FGPzlsm1ezfL0gPIS9umBw2SxQ-TdJJWK-cllWuuW7U
@travelToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImNhbXBJZCI6MSwicm9sIjoiVFJBVkVMX01BTkFHRVIiLCJqdGkiOiI2YWVjMzg4OC0zMTc0LTRlYTktYTgwYi05MmMyZGM2ZDQyMWEiLCJpYXQiOjE3NzU2MzQxNDUsImV4cCI6MTc3NTYzNTM0NX0.ykGLA0KJvOE7v7WCbVdnup8S35OIuoxvyMiy02V5Ydw
@workerToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImNhbXBJZCI6MSwicm9sIjoiVklTSVRPUiIsImp0aSI6IjNjNzExNmNjLWQyMzYtNDJkYy05NGFlLTVlZTA4M2NlYjJiMiIsImlhdCI6MTc3NTYzNDE1NywiZXhwIjoxNzc1NjM1MzU3fQ.X7-9QJBRbSvQIF2F0auHHorZlEsUNZRXbH_OmMmVBDI

### SECTION 2: DASHBOARD RBAC

### 7. [SHOULD 200] GET: Admin accesses /api/dashboard/general
GET {{baseUrl}}/api/dashboard/general
Authorization: Bearer {{adminToken}}

###

### 8. [SHOULD 403] GET: Worker accesses /api/dashboard/general
GET {{baseUrl}}/api/dashboard/general
Authorization: Bearer {{workerToken}}

###

### 9. [SHOULD 200] GET: Resource Management accesses /api/dashboard/inventory
GET {{baseUrl}}/api/dashboard/inventory
Authorization: Bearer {{resourceToken}}

###

### 10. [SHOULD 403] GET: Worker accesses /api/dashboard/inventory
GET {{baseUrl}}/api/dashboard/inventory
Authorization: Bearer {{workerToken}}

###

### 11. [SHOULD 200] GET: Travel Manager accesses /api/dashboard/expeditions
GET {{baseUrl}}/api/dashboard/expeditions
Authorization: Bearer {{travelToken}}
